[general]
default-layout='brisk-menu-stand-alone-bottom'
object-id-list=['main-menu', 'file-manager', 'text-editor', 'web-brower', 'terminal', 'control-center', 'show-desktop', 'window-list', 'workspace-switcher', 'notification-area', 'clock']
toplevel-id-list=['main-panel']

[objects/clock]
applet-iid='ClockAppletFactory::ClockApplet'
locked=true
object-type='applet'
panel-right-stick=true
position=0
relative-to-edge='end'
toplevel-id='main-panel'

[objects/clock/prefs]
custom-format=''
format='24-hour'

[objects/control-center]
launcher-location='/usr/share/applications/matecc.desktop'
locked=true
object-type='launcher'
position=15
toplevel-id='main-panel'

[objects/file-manager]
launcher-location='/usr/share/applications/pcmanfm-qt.desktop'
locked=true
object-type='launcher'
position=11
toplevel-id='main-panel'

[objects/main-menu]
applet-iid='BriskMenuFactory::BriskMenu'
locked=true
object-type='applet'
position=0
toplevel-id='main-panel'

[objects/notification-area]
applet-iid='NotificationAreaAppletFactory::NotificationArea'
locked=true
object-type='applet'
panel-right-stick=true
position=10
relative-to-edge='end'
toplevel-id='main-panel'

[objects/show-desktop]
applet-iid='WnckletFactory::ShowDesktopApplet'
locked=true
object-type='applet'
position=16
toplevel-id='main-panel'

[objects/terminal]
launcher-location='/usr/share/applications/sakura.desktop'
locked=true
object-type='launcher'
position=14
toplevel-id='main-panel'

[objects/text-editor]
launcher-location='/usr/share/applications/org.xfce.mousepad.desktop'
locked=true
object-type='launcher'
position=12
toplevel-id='main-panel'

[objects/web-brower]
launcher-location='/usr/share/applications/firefox-esr.desktop'
locked=true
object-type='launcher'
position=13
toplevel-id='main-panel'

[objects/window-list]
applet-iid='WnckletFactory::WindowListApplet'
locked=true
object-type='applet'
position=20
toplevel-id='main-panel'

[objects/workspace-switcher]
applet-iid='WnckletFactory::WorkspaceSwitcherApplet'
locked=true
object-type='applet'
panel-right-stick=true
position=20
relative-to-edge='end'
toplevel-id='main-panel'

[toplevels/main-panel]
expand=true
orientation='bottom'
screen=0
size=24
y=744
y-bottom=0
